CREATE TABLE ZEI(
   ID_ZEI VARCHAR(50),
   CODE_ZEI VARCHAR(50),
   VILLE_ZEI VARCHAR(50),
   PRIMARY KEY(ID_ZEI, CODE_ZEI)
);

CREATE TABLE SOUS_TRAITANT(
   ID_SOUS_TRAITANT COUNTER,
   CODE_SOUS_TRAITANT VARCHAR(50),
   NOM_SOUS_TRAITANT VARCHAR(50),
   ADRESSE_SOUS_TRAITANT VARCHAR(50),
   PRIMARY KEY(ID_SOUS_TRAITANT, CODE_SOUS_TRAITANT)
);

CREATE TABLE DEMANDE(
   ID_DEMANDE VARCHAR(50),
   REFERENCE_DEMANDE VARCHAR(50),
   NOM_CLIENT_DEMANDE VARCHAR(50),
   PRENOM_CLIENT_DEMANDE VARCHAR(50),
   ADRESSE_CLIENT_DEMANDE VARCHAR(50),
   TEL_CLIENT_DEMANDE VARCHAR(50),
   RUE_TRAVAUX_DEMANDE VARCHAR(50),
   NOM_LOTISSEMENT_DEMANDE VARCHAR(50),
   COMMUNE_TRAVAU_DEMANDE VARCHAR(50),
   PRIMARY KEY(ID_DEMANDE, REFERENCE_DEMANDE)
);

CREATE TABLE AGENT(
   ID_AGENT COUNTER,
   MATRICULE_AGENT VARCHAR(50),
   NOM_AGENT VARCHAR(50),
   PRENOM_AGENT VARCHAR(50),
   PRIMARY KEY(ID_AGENT, MATRICULE_AGENT)
);

CREATE TABLE JOUR(
   ID_JOUR COUNTER,
   JOUR VARCHAR(50),
   PRIMARY KEY(ID_JOUR)
);

CREATE TABLE DEVIS(
   ID_DEVIS VARCHAR(50),
   NUMERO_DEVIS VARCHAR(50),
   DATE_DEVIS DATE,
   NONTANT_ESTIME_DEVIS VARCHAR(50),
   PRIMARY KEY(ID_DEVIS, NUMERO_DEVIS)
);

CREATE TABLE OPERATION(
   ID_OPERATION COUNTER,
   CODE_OPERATION VARCHAR(50),
   LIBELLE_OPERATION VARCHAR(50),
   POIDS_OPERATION DATETIME,
   PRIMARY KEY(ID_OPERATION, CODE_OPERATION)
);

CREATE TABLE SOUS_CATEGORIE(
   ID_SOUS_CATEGORIE COUNTER,
   CODE_SOUS_CATEGORIE VARCHAR(50),
   LIBELLE_SOUS_CATEGORIE VARCHAR(50),
   PRIMARY KEY(ID_SOUS_CATEGORIE, CODE_SOUS_CATEGORIE)
);

CREATE TABLE CATEGORIE(
   ID_CATEGORIE VARCHAR(50),
   CODE_CATEGORIE VARCHAR(50),
   DESIGNATION_CATEGORIE VARCHAR(50),
   PRIMARY KEY(ID_CATEGORIE, CODE_CATEGORIE)
);

CREATE TABLE NEUF(
   ID_DEMANDE_NEUF VARCHAR(50),
   DATE_AMMENAGEMENT_DEMANDE VARCHAR(50),
   ID_DEMANDE VARCHAR(50) NOT NULL,
   REFERENCE_DEMANDE VARCHAR(50) NOT NULL,
   PRIMARY KEY(ID_DEMANDE_NEUF),
   UNIQUE(ID_DEMANDE),
   UNIQUE(REFERENCE_DEMANDE),
   FOREIGN KEY(ID_DEMANDE, REFERENCE_DEMANDE) REFERENCES DEMANDE(ID_DEMANDE, REFERENCE_DEMANDE)
);

CREATE TABLE MODIFICATION(
   ID_MODIFICATION VARCHAR(50),
   ID_DEMANDE VARCHAR(50) NOT NULL,
   REFERENCE_DEMANDE VARCHAR(50) NOT NULL,
   PRIMARY KEY(ID_MODIFICATION),
   UNIQUE(ID_DEMANDE),
   UNIQUE(REFERENCE_DEMANDE),
   FOREIGN KEY(ID_DEMANDE, REFERENCE_DEMANDE) REFERENCES DEMANDE(ID_DEMANDE, REFERENCE_DEMANDE)
);

CREATE TABLE PROVISOIRE(
   ID_PROVISOIRE VARCHAR(50),
   DATE_DEBUT_BRANCHEMENT VARCHAR(50),
   DATE_FIN_BRANCHIT VARCHAR(50),
   ID_DEMANDE VARCHAR(50) NOT NULL,
   REFERENCE_DEMANDE VARCHAR(50) NOT NULL,
   PRIMARY KEY(ID_PROVISOIRE),
   UNIQUE(ID_DEMANDE),
   UNIQUE(REFERENCE_DEMANDE),
   FOREIGN KEY(ID_DEMANDE, REFERENCE_DEMANDE) REFERENCES DEMANDE(ID_DEMANDE, REFERENCE_DEMANDE)
);

CREATE TABLE MAITRE_OEUVRE(
   ID_MAITRE_OEUVRE VARCHAR(50),
   CODE_MAITRE_OEUVRE VARCHAR(50),
   NOM_MAITRE_OEUVRE VARCHAR(50),
   ADRESSE_MAITRE_OEUVRE VARCHAR(50),
   TELEPHONE_MAITRE_OEUVRE VARCHAR(50),
   PRIMARY KEY(ID_MAITRE_OEUVRE, CODE_MAITRE_OEUVRE)
);

CREATE TABLE ELECTRICIEN(
   ID_ELECTRICIEN VARCHAR(50),
   CODE_ELECTRICIEN VARCHAR(50),
   NOM_ELECTRICIEN VARCHAR(50),
   ADRESSE_ELECTRICIEN VARCHAR(50),
   TELEPHONE_ELECTRICIEN VARCHAR(50),
   PRIMARY KEY(ID_ELECTRICIEN, CODE_ELECTRICIEN)
);

CREATE TABLE CONTRAT(
   ID_CONTRAT COUNTER,
   NUMERO_CONTRAT VARCHAR(50),
   ID_SOUS_TRAITANT INT NOT NULL,
   CODE_SOUS_TRAITANT VARCHAR(50) NOT NULL,
   PRIMARY KEY(ID_CONTRAT, NUMERO_CONTRAT),
   FOREIGN KEY(ID_SOUS_TRAITANT, CODE_SOUS_TRAITANT) REFERENCES SOUS_TRAITANT(ID_SOUS_TRAITANT, CODE_SOUS_TRAITANT)
);

CREATE TABLE travailler(
   ID_CONTRAT INT,
   NUMERO_CONTRAT VARCHAR(50),
   ID_ZEI VARCHAR(50),
   CODE_ZEI VARCHAR(50),
   ID_JOUR INT,
   PRIMARY KEY(ID_CONTRAT, NUMERO_CONTRAT, ID_ZEI, CODE_ZEI, ID_JOUR),
   FOREIGN KEY(ID_CONTRAT, NUMERO_CONTRAT) REFERENCES CONTRAT(ID_CONTRAT, NUMERO_CONTRAT),
   FOREIGN KEY(ID_ZEI, CODE_ZEI) REFERENCES ZEI(ID_ZEI, CODE_ZEI),
   FOREIGN KEY(ID_JOUR) REFERENCES JOUR(ID_JOUR)
);

CREATE TABLE Aboutir(
   ID_DEMANDE VARCHAR(50),
   REFERENCE_DEMANDE VARCHAR(50),
   ID_DEVIS VARCHAR(50),
   NUMERO_DEVIS VARCHAR(50),
   PRIMARY KEY(ID_DEMANDE, REFERENCE_DEMANDE, ID_DEVIS, NUMERO_DEVIS),
   FOREIGN KEY(ID_DEMANDE, REFERENCE_DEMANDE) REFERENCES DEMANDE(ID_DEMANDE, REFERENCE_DEMANDE),
   FOREIGN KEY(ID_DEVIS, NUMERO_DEVIS) REFERENCES DEVIS(ID_DEVIS, NUMERO_DEVIS)
);

CREATE TABLE Rediger(
   ID_AGENT INT,
   MATRICULE_AGENT VARCHAR(50),
   ID_DEVIS VARCHAR(50),
   NUMERO_DEVIS VARCHAR(50),
   PRIMARY KEY(ID_AGENT, MATRICULE_AGENT, ID_DEVIS, NUMERO_DEVIS),
   FOREIGN KEY(ID_AGENT, MATRICULE_AGENT) REFERENCES AGENT(ID_AGENT, MATRICULE_AGENT),
   FOREIGN KEY(ID_DEVIS, NUMERO_DEVIS) REFERENCES DEVIS(ID_DEVIS, NUMERO_DEVIS)
);

CREATE TABLE Necessiter(
   ID_DEMANDE VARCHAR(50),
   REFERENCE_DEMANDE VARCHAR(50),
   ID_OPERATION INT,
   CODE_OPERATION VARCHAR(50),
   PRIMARY KEY(ID_DEMANDE, REFERENCE_DEMANDE, ID_OPERATION, CODE_OPERATION),
   FOREIGN KEY(ID_DEMANDE, REFERENCE_DEMANDE) REFERENCES DEMANDE(ID_DEMANDE, REFERENCE_DEMANDE),
   FOREIGN KEY(ID_OPERATION, CODE_OPERATION) REFERENCES OPERATION(ID_OPERATION, CODE_OPERATION)
);

CREATE TABLE Localiser(
   ID_ZEI VARCHAR(50),
   CODE_ZEI VARCHAR(50),
   ID_DEMANDE VARCHAR(50),
   REFERENCE_DEMANDE VARCHAR(50),
   PRIMARY KEY(ID_ZEI, CODE_ZEI, ID_DEMANDE, REFERENCE_DEMANDE),
   FOREIGN KEY(ID_ZEI, CODE_ZEI) REFERENCES ZEI(ID_ZEI, CODE_ZEI),
   FOREIGN KEY(ID_DEMANDE, REFERENCE_DEMANDE) REFERENCES DEMANDE(ID_DEMANDE, REFERENCE_DEMANDE)
);

CREATE TABLE Rattacher(
   ID_OPERATION INT,
   CODE_OPERATION VARCHAR(50),
   ID_SOUS_CATEGORIE INT,
   CODE_SOUS_CATEGORIE VARCHAR(50),
   PRIMARY KEY(ID_OPERATION, CODE_OPERATION, ID_SOUS_CATEGORIE, CODE_SOUS_CATEGORIE),
   FOREIGN KEY(ID_OPERATION, CODE_OPERATION) REFERENCES OPERATION(ID_OPERATION, CODE_OPERATION),
   FOREIGN KEY(ID_SOUS_CATEGORIE, CODE_SOUS_CATEGORIE) REFERENCES SOUS_CATEGORIE(ID_SOUS_CATEGORIE, CODE_SOUS_CATEGORIE)
);

CREATE TABLE Appartenir(
   ID_SOUS_CATEGORIE INT,
   CODE_SOUS_CATEGORIE VARCHAR(50),
   ID_CATEGORIE VARCHAR(50),
   CODE_CATEGORIE VARCHAR(50),
   PRIMARY KEY(ID_SOUS_CATEGORIE, CODE_SOUS_CATEGORIE, ID_CATEGORIE, CODE_CATEGORIE),
   FOREIGN KEY(ID_SOUS_CATEGORIE, CODE_SOUS_CATEGORIE) REFERENCES SOUS_CATEGORIE(ID_SOUS_CATEGORIE, CODE_SOUS_CATEGORIE),
   FOREIGN KEY(ID_CATEGORIE, CODE_CATEGORIE) REFERENCES CATEGORIE(ID_CATEGORIE, CODE_CATEGORIE)
);

CREATE TABLE Suivre(
   ID_DEMANDE_NEUF VARCHAR(50),
   ID_MAITRE_OEUVRE VARCHAR(50),
   CODE_MAITRE_OEUVRE VARCHAR(50),
   PRIMARY KEY(ID_DEMANDE_NEUF, ID_MAITRE_OEUVRE, CODE_MAITRE_OEUVRE),
   FOREIGN KEY(ID_DEMANDE_NEUF) REFERENCES NEUF(ID_DEMANDE_NEUF),
   FOREIGN KEY(ID_MAITRE_OEUVRE, CODE_MAITRE_OEUVRE) REFERENCES MAITRE_OEUVRE(ID_MAITRE_OEUVRE, CODE_MAITRE_OEUVRE)
);

CREATE TABLE Installer(
   ID_DEMANDE_NEUF VARCHAR(50),
   ID_ELECTRICIEN VARCHAR(50),
   CODE_ELECTRICIEN VARCHAR(50),
   PRIMARY KEY(ID_DEMANDE_NEUF, ID_ELECTRICIEN, CODE_ELECTRICIEN),
   FOREIGN KEY(ID_DEMANDE_NEUF) REFERENCES NEUF(ID_DEMANDE_NEUF),
   FOREIGN KEY(ID_ELECTRICIEN, CODE_ELECTRICIEN) REFERENCES ELECTRICIEN(ID_ELECTRICIEN, CODE_ELECTRICIEN)
);
